config/routes.rb
Rails.application.routes.draw do
  root 'lists#main'
  resources :lists
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/:id', to: 'users#show'
end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :list
  has_many :list_items, dependent: :destroy
  accepts_nested_attributes_for :list_items, allow_destroy: true
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :elements, dependent: :destroy
  accepts_nested_attributes_for :elements, allow_destroy: true
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :element
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, :except => [:main]

  def main
    if user_signed_in?
      redirect_to "/users/#{current_user.id}"
    end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
  @list = List.find(params[:id])

    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @list = current_user.lists.find(params[:id])
    @elements = @list.elements.order("order_number ASC")
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to "/users/#{current_user.id}"
  end

  private
    def list_params
      params.require(:list).permit(:id, :name, :properties => [], elements_attributes: [:id, :list_id, :order_number, :element_type, :content, :_destroy, list_items_attributes: [:id, :element_id, :order_number, :list_type, :content, :_destroy]])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association, element_type)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id

    # order_number = order_numbering(f.object)
    # p order_number
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render element_type, f: builder, element_type: element_type
    end

    if element_type != "list_item"
      namespace = f.object.elements.length
      link_to(name, '#', class: "add_element", data: {id: id, fields: fields.gsub("\n", ""), namespace: namespace})
    else
      namespace = f.object.list_items.length
      link_to(name, '#', class: "add_list_item", data: {id: id, fields: fields.gsub("\n", ""), namespace: namespace})
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ListGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_right" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" id="brand" href="/">List Generator</a>
        <% if user_signed_in? %>
          <p class="navbar-text">Hello <%= current_user.first_name %>!</p>
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="nav_right">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a href="/users/edit">Settings</a></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><a href="/users/sign_in">Log In</a></li>
            <li><a href="/users/sign_up">Sign Up</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <%= yield %>

</body>
</html>

app/views/lists/_form.html.haml
= form_for @list do |f|
  - if @list.errors.any?
    #errors_explanations
      %h2= "#{pluralize(@lists.errors.count, "error")} prohibited this product_type from being saved"
      %ul
        -@lists.errors.full_messages.each do |message|
          %li= message
  .form-group.text-center.row
    = f.label :name
    %br
    = f.text_field :name, class: "col-md-6 col-md-offset-3 input-sm"

  = f.fields_for :elements do |a|
    = render a.object.element_type, f: a, element_type: a.object.element_type

  .row
    .col-md-8.col-md-offset-2.element_links
      %p
        = link_to_add_fields "Add Text Field", f, :elements, "text"
        |
        = link_to_add_fields "Add Numbered List", f, :elements, "numbered_list"
        |
        = link_to_add_fields "Add Unordered List", f, :elements, "unordered_list"
      %br
      .actions
        = f.submit "Submit", class: "btn btn-primary"

app/views/lists/_list_item.html.haml
.form-group.text-center
  %li
    = f.hidden_field :list_type, value: element_type
    .row
      = f.text_field :content, class: "col-md-4 col-md-offset-2", rows: "6", placeholder: "Type your stuff"
      = f.hidden_field :order_number, class: "order_number"
      = f.hidden_field :_destroy
      = link_to "[Remove Item]", "#", class: "remove_element col-md-2"

app/views/lists/_numbered_list.html.haml
.form-group.text-center
  = f.hidden_field :element_type, value: element_type
  = f.label "Numbered List"
  %br
  %ol
  = f.hidden_field :order_number, class: "order_number"
  = f.hidden_field :_destroy
  = link_to "[Remove]", "#", class: "remove_element"
  %br

app/views/lists/_text.html.haml
.form-group.text-center
  = f.hidden_field :element_type, value: element_type
  = f.label "Text"
  %br
  .row
    = f.text_area :content, class: "col-md-8 col-md-offset-2", rows: "6", placeholder: "Type your stuff"
  = f.hidden_field :order_number, class: "order_number"
  = f.hidden_field :_destroy
  = link_to "[Remove From List]", "#", class: "remove_element"
  %br
  .row
    .col-md-8.col-md-offset-2
      %hr

app/views/lists/_unordered_list.html.haml
.form-group.text-center
  = f.hidden_field :element_type, value: element_type
  = f.label "Unordered List"
  %br
  = f.hidden_field :order_number, class: "order_number", value: ""
  = f.hidden_field :_destroy
  %ul.form_list
    = f.fields_for :list_items do |a|
      = render "list_item", f: a, element_type: element_type
    .list_item_link
      = link_to_add_fields "Add List Item", f, :list_items, "list_item"
  = link_to "[Remove From List]", "#", class: "remove_element"
  %br
  .row
    .col-md-8.col-md-offset-2
      %hr

app/views/lists/edit.html.haml
%h2.text-center= "Edit List"
%br
.container
  = render "form"
  %br
  .row
    .col-md-8.col-md-offset-2
      = link_to "Back", "/users/#{current_user.id}", class: "btn btn-default"
  %br

app/views/lists/main.html.haml
.jumbotron
  .jumbotron_background
    %h1.text-center.jumbo_text= "List Generator"
    %p.text-center.jumbo_text= "In progress..."
.container
  .row
    .col-md-6
      .main_img#img1
    .col-md-6
      %h3.text-center= "Create Custom Documents"
      %p= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec orci scelerisque, tempus eros sed, bibendum ex. Duis nulla diam, luctus nec libero at, auctor ornare massa. Nulla vitae lorem eu sem iaculis gravida. Nunc porttitor vehicula iaculis. Sed nec faucibus eros. Maecenas volutpat dui sit amet pharetra dignissim. In ac velit placerat, vehicula enim non, mollis justo. Sed faucibus tempor ex, in consectetur erat laoreet non."
.main2
  .container
    .row
      .col-md-6
        %h3.text-center= "Save To PDF"
        %p= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec orci scelerisque, tempus eros sed, bibendum ex. Duis nulla diam, luctus nec libero at, auctor ornare massa. Nulla vitae lorem eu sem iaculis gravida. Nunc porttitor vehicula iaculis. Sed nec faucibus eros. Maecenas volutpat dui sit amet pharetra dignissim. In ac velit placerat, vehicula enim non, mollis justo. Sed faucibus tempor ex, in consectetur erat laoreet non."
      .col-md-6
        .main_img#img2
.container
  .row
    .col-md-6
      .main_img#img3
    .col-md-6
      %h3.text-center= "Something Else!"
      %p= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec orci scelerisque, tempus eros sed, bibendum ex. Duis nulla diam, luctus nec libero at, auctor ornare massa. Nulla vitae lorem eu sem iaculis gravida. Nunc porttitor vehicula iaculis. Sed nec faucibus eros. Maecenas volutpat dui sit amet pharetra dignissim. In ac velit placerat, vehicula enim non, mollis justo. Sed faucibus tempor ex, in consectetur erat laoreet non."
.container-fluid.footer
  %p.text-center= "Fill this in later."

app/views/lists/new.html.haml
%h2.text-center= "Create New Document"
%br
.container
  = render "form"
  %br
  = link_to "Back", "/users/#{current_user.id}"

app/views/lists/show.html.haml
.container
  %h1.text-center= @list.name
  %p.text-center= "Created: #{@list.created_at.strftime("%m-%d-%y")} | Last Updated: #{@list.updated_at.strftime("%m-%d-%y")}"
  %p.text-center
    = link_to "Edit", edit_list_path(@list.id)
    |
    = link_to 'Delete', "/lists/#{@list.id}", data: {confirm: "Are you sure you want to delete this list?"} , method: :delete
  %br
  - @elements.each do |a|
    - if a.element_type == "text"
      %p= a.content
      %br
    - elsif a.element_type == "unordered_list"
      - if a.list_items != nil
        %ul
          - a.list_items.each do |i|
            %li= i.content

app/views/users/show.html.haml
.container
  %h2.text-center= "Manage Lists"
  %br
  .text-center
    = link_to "Create New List", new_list_path, class: "btn btn-default"
  %br
  .row
    .col-md-5.col-md-offset-2.col-sm-5.col-sm-offset-2.col-xs-5.col-xs-offset-2
      %h4.underline= "Title"
    .col-md-1.col-sm-1.col-xs-1.hidden-xs.hidden-sm
      %h4.underline= "Created"
    .col-md-1.col-sm-1.col-xs-1.hidden-xs.hidden-sm
      %h4.underline= "Edited"
    .col-md-1.col-sm-1.col-xs-1
      %h4.underline= "Options"
  - @user.lists.each do |a|
    .row
      .col-md-5.col-md-offset-2.col-sm-5.col-sm-offset-2.col-xs-5.col-xs-offset-2
        %p
          = link_to a.name, list_path(a.id), class: "link_mod"
      .col-md-1.col-sm-1.col-xs-1.hidden-xs.hidden-sm
        %p.text-center= a.created_at.strftime("%m-%d-%y")
      .col-md-1.col-sm-1.col-xs-1.hidden-xs.hidden-sm
        - if a.updated_at != a.created_at
          %p= a.updated_at.strftime("%m-%d-%y")
        - else
          %p= "------------"
      .col-md-2.col-sm-1.col-xs-1
        %p
          = link_to "Edit", edit_list_path(a.id)
          |
          = link_to 'Delete', "/lists/#{a.id}", data: {confirm: "Are you sure you want to delete this list?"} , method: :delete